apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-property-platform
  labels:
    app: crm-property-platform

spec:
  replicas: 1
  selector:
    matchLabels:
      app: crm-property-platform

  template:
    metadata:
      labels:
        app: crm-property-platform

    spec:
      containers:
        - name: crm-property-platform
          image: sumit244/crm-property-platform:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DATABASE_URL

            - name: EMAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: EMAIL_HOST
            - name: EMAIL_PORT
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: EMAIL_PORT
            - name: EMAIL_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: EMAIL_USER
            - name: EMAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: EMAIL_PASS
            - name: EMAIL_FROM
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: EMAIL_FROM
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: JWT_SECRET